# Generated by Django 5.1.6 on 2025-02-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elec_name',
            name='Election_Month',
            field=models.CharField(default='Janury', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='OTP_Count',
            field=models.IntegerField(default=1),
        ),
    ]
